# Project information
site_name: CodePoint
site_description: >-
  Expert Sheet Solutions in C++, Java, and Python.
site_author: Akash Singh
site_url: https://prepverse.github.io/CodePoint

# Repository
repo_name: CodePoint
repo_url: https://github.com/PrepVerse/CodePoint

# Copyright
copyright: Copyright &copy; 2022 - 2023 <a href="http://github.com/AkashSingh3031"> Akash Singh </a>

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: cyan
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: fontawesome/solid/laptop-code
    repo: fontawesome/brands/github

# Plugins
plugins:
  # - blog:
  #     blog_dir: blog/posts
  #     post_date_format: medium
  #     post_url_date_format: yyyy/MM/dd
  #     post_url_format: "{date}/{slug}"
  #     post_readtime_words_per_minute: 265
  #     post_slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower
  #     post_slugify_separator: "-"
  #     authors_file: .authors.yml
  #     enabled: !ENV [CodePoint, false]
  # - git-authors:
  #       # show_contribution: true
  #     exclude:
  #       - index.md
  #       - preface.md
  # # - git-committers:
  # #     repository: PrepVerse/CodePoint
  # #     branch: master
  # - git-revision-date-localized:
  #     type: timeago
  #     # custom_format: "%-d. %B %Y"
  #     # timezone: Asia
  #     # locale: en
  #     fallback_to_build_date: true
  #     enable_creation_date: true
  # - meta
  - minify:
      minify_html: true
  - search
  - tags
  # - redirects:
  #     redirect_maps:

# Customization
extra:
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
    provider: google
    property: G-JF4ZWKWVGC
  comments:
    enabled: true
    # defaults to utterances unless replaced with mode: giscus
    mode: giscus
    # mode: utterances
    # type: issues
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AkashSingh3031
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/akashsingh3031
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/akash.singh3031
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/akashsingh3031

extra_css:
  - css/katex.css
  - css/custom.css
  - css/childpages_card_grid.css
  - https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css

extra_javascript:
  - js/feedback.js
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/contrib/auto-render.min.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx.table
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: akashsingh3031
      repo: CodePoint
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: 
    - Home: index.md
  - Expert Sheet Solutions:
    - Preface: preface.md
    - Striver Series:
      - DSA:
        - Striver A2Z DSA Sheet:
          - 1. Learn the basics: 
            - 1.1. Things to Know: 
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/User_Input-Output.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/Data-Types.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/If-Else-Statements.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/Switch-Statement.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/What-are-Arrays-Strings.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/For-Loops.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/While-Loops.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/Functions.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/Time-Complexity.md
            - 1.2. Pattern Problems:
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-1.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-2.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-3.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-4.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-5.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-6.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-7.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-8.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-9.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-10.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-11.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-12.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-13.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-14.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-15.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-16.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-17.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-18.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-19.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-20.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-21.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-22.md
            - 1.3. C++ STL:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.3/CPP-STL.md
            - 1.4. Basic Maths:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Count-Digits.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Reverse-a-Number.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Check-Palindrome.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/GCD-and-LCM.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Armstrong-Numbers.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Print-all-Divisors.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Check-for-Prime.md
            - 1.5. Basic Recursion:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Undestand-Recursion.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Print-Name-N-times.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Print-1-to-N.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Print-N-to-1.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Sum-of-first-N-numbers.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Factorial-of-N-numbers.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Reverse-an-array.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Check-if-a-string-is-palindrome-or-not.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Fibonacci-Number.md
            - 1.6. Basic Hashing:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.6/Counting-Frequencies-of-Array-Elements.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.6/Find-the-highest_lowest-frequency-element.md
          - 2. Sorting Techiques: 
            - 2.1. Sorting-I: 
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.1/Selection-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.1/Bubble-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.1/Insertion-Sort.md
            - 2.2. Sorting-II: 
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.2/Merge-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.2/Recursive-Bubble-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.2/Recursive-Insertion-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.2/Quick-Sort.md
      - CSE Fundamentals:
        - Striver SDE Core Sheet:
          - learning_resources/codepoint/striver_core_sde_sheet_solution/operating_system/OS.md
  - Coding Ninjas Series:
    - learning_resources/CN_Series/preface.md
    - Placement Preparation:
      - Phase 1:
        - 1. Aptitude:
          - 1.1. Logical Reasoning:
            - Module 1:
              - learning_resources/CN_Series/Phase1/Aptitude/Logical_Reasoning/Module1/Alphanumeric_Series.md
              - learning_resources/CN_Series/Phase1/Aptitude/Logical_Reasoning/Module1/Artificial_Language.md
            # - Module 2:
            #   - learning_resources/CN_Series/Phase1/Aptitude/Logical_Reasoning/Module2/Deductive_Reasoning.md
            # - Module 3:
            #   - learning_resources/CN_Series/Phase1/Aptitude/Logical_Reasoning/Module3/MIrror_Water_Images.md
  #       - 2. Puzzle:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #     - Phase 2:
  #       - Basic Programming:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - Basic Programming - Test:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - OOP:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - DSA:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - DSA - Test:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - Topic wise Problems:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #     - Phase 3:
  #       - OS:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - DBMS:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - CN:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - CSE Fundamentals - Test:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - System Design:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #     - Phase 4:
  #       - CP:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - CP - Test:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - Web Development:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - Data Science:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  # - Free Cources:
  #   - DSA:
  #     - Striver Series:
  #       - learning_resources/Free_Courses/Striver_Series/DSA.md
  #     - Love Babbar Series:
  #       - learning_resources/Free_Courses/Love_Babbar_Series/DSA.md
  #     - Apna College Series:
  #       - learning_resources/Free_Courses/Apna_College_Series/DSA.md
  #   - Theory:
  #     - Love Babbar Series:
  #       - learning_resources/Free_Courses/Love_Babbar_Series/DSA.md
  #     - Apna College Series:
  #       - learning_resources/Free_Courses/Apna_College_Series/DSA.md
  # - Blog:
  #   - learning_resources/blog/index.md
  #   - Python:
  #     - NumPy:
  #       - learning_resources/blog/posts/NumPy.md
  - About Me: about/about.md
