# Project information
site_name: CodePoint
site_description: >-
  Expert Sheet Solutions in C++, Java, and Python.
site_author: Akash Singh
site_url: https://prepverse.github.io/CodePoint

# Repository
repo_name: CodePoint
repo_url: https://github.com/PrepVerse/CodePoint

# Copyright
copyright: Copyright &copy; 2022 - 2023 <a href="http://github.com/AkashSingh3031"> Akash Singh </a>

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  language: en
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  icon:
    logo: fontawesome/solid/laptop-code
    repo: fontawesome/brands/github
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: cyan
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  pymdownx:
    sponsor: "https://github.com/sponsors/AkashSingh3031"

# Plugins
plugins:
  - blog:
      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      archive_url_format: "archive/{date}"
      archive_toc: true
      authors: true
      authors_file: "{blog}/.authors.yml"
      blog_dir: learning_resources/blog
      blog_toc: true
      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      categories_slugify_separator: _
      categories_toc: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_if_single_page: true
      pagination_per_page: 5
      pagination_url_format: "page/{page}"
      post_dir: "{blog}/posts"
      post_date_format: long
      post_excerpt: optional
      post_excerpt_max_authors: 1
      post_excerpt_max_categories: 5
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify_separator: "-"
      post_url_date_format: yyyy/MM/dd
      # post_url_format: "{date}/{slug}"
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 2
      post_readtime: true
      post_readtime_words_per_minute: 250
  #     enabled: !ENV [CodePoint, false]
  # - git-authors:
  #     show_contribution: true
  #     exclude:
  #       - index.md
  # - git-committers:
  #     repository: PrepVerse/CodePoint
  #     branch: master
  # - git-revision-date-localized:
  #     # custom_format: "%d. %B %Y"
  #     # enabled: !ENV [CodePoint, false]
  #     # enable_creation_date: true
  #     # fallback_to_build_date: true
  #     # locale: en
  #     # timezone: Asia
  #     # type: timeago
  #     # exclude:
  #     #     - index.md
  # - glightbox
  # - meta
  - minify:
      minify_html: true
  # - redirects:
  #     redirect_maps:
  - search
  # - social
  - swagger-ui-tag
  - tags:
      tags_file: learning_resources/tags/tags.md

# Customization
extra:
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://prepverse.github.io/#contact" target="_blank" rel="noopener">feedback form</a>.
    provider: google
    property: G-JF4ZWKWVGC
  comments:
    enabled: true
    # defaults to utterances unless replaced with mode: giscus
    mode: giscus
    # mode: utterances
    # type: issues
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AkashSingh3031
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/akashsingh3031
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/akash.singh3031
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/akashsingh3031
  tags:
    HTML5: html
    JavaScript: js
    CSS: css

extra_css:
  - css/childpages_card_grid.css
  - css/custom.css
  - css/extra.css
  - css/katex.css
  - css/progressbar.css
  # - css/pymdownx_extras.css
  - https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - js/feedback.js
  - js/katex.js
  - js/repo_card.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/contrib/auto-render.min.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab:
      alternate_style: True
      combine_header_slug: True
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx.table
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: PrepVerse
      repo: CodePoint
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # - tools.collapse_code:
  #     expand_text: ''
  #     collapse_text: ''

nav:
  - Home: 
    - Home: index.md
  - Expert Sheet Solutions:
    - Preface: preface.md
    - Striver Sheets:
      - DSA:
        - Striver A2Z DSA Sheet:
          - 1. Learn the basics: 
            - 1.1. Things to Know:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/Video-Solution.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/User_Input-Output.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/Data-Types.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/If-Else-Statements.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/Switch-Statement.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/What-are-Arrays-Strings.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/For-Loops.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/While-Loops.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/Functions.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.1/Time-Complexity.md
            - 1.2. Pattern Problems:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Video-Solution.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-1.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-2.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-3.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-4.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-5.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-6.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-7.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-8.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-9.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-10.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-11.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-12.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-13.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-14.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-15.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-16.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-17.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-18.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-19.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-20.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-21.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.2/Pattern_Problems/Pattern-22.md
            - 1.3. C++ STL:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.3/Video-Solution.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.3/CPP-STL.md
            - 1.4. Basic Maths:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Video-Solution.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Count-Digits.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Reverse-a-Number.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Check-Palindrome.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/GCD-and-LCM.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Armstrong-Numbers.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Print-all-Divisors.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.4/Check-for-Prime.md
            - 1.5. Basic Recursion:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Video-Solution.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Undestand-Recursion.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Print-Name-N-times.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Print-1-to-N.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Print-N-to-1.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Sum-of-first-N-numbers.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Factorial-of-N-numbers.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Reverse-an-array.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Check-if-a-string-is-palindrome-or-not.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.5/Fibonacci-Number.md
            - 1.6. Basic Hashing:
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.6/Video-Solution.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.6/Counting-Frequencies-of-Array-Elements.md
              - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step01/step1.6/Find-the-highest_lowest-frequency-element.md
          - 2. Sorting Techiques: 
            - 2.1. Sorting-I: 
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.1/Selection-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.1/Bubble-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.1/Insertion-Sort.md
            - 2.2. Sorting-II: 
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.2/Merge-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.2/Recursive-Bubble-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.2/Recursive-Insertion-Sort.md
                - learning_resources/codepoint/striver_a2z_dsa_sheet_solution/step02/step2.2/Quick-Sort.md
      - CSE Fundamentals:
        - Striver SDE Core Sheet:
          - learning_resources/codepoint/striver_core_sde_sheet_solution/operating_system/OS.md
  - Coding Ninjas Series:
    - learning_resources/CN_Series/preface.md
    - Placement Preparation:
      - Phase 1:
        - 1. Aptitude:
          - 1.1. Logical Reasoning:
            - Module 1:
              - learning_resources/CN_Series/Phase1/Aptitude/Logical_Reasoning/Module1/Alphanumeric_Series.md
              - learning_resources/CN_Series/Phase1/Aptitude/Logical_Reasoning/Module1/Artificial_Language.md
            # - Module 2:
            #   - learning_resources/CN_Series/Phase1/Aptitude/Logical_Reasoning/Module2/Deductive_Reasoning.md
            # - Module 3:
            #   - learning_resources/CN_Series/Phase1/Aptitude/Logical_Reasoning/Module3/Mirror_Water_Images.md
  #       - 2. Puzzle:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #     - Phase 2:
  #       - Basic Programming:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - Basic Programming - Test:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - OOP:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - DSA:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - DSA - Test:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - Topic wise Problems:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #     - Phase 3:
  #       - OS:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - DBMS:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - CN:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - CSE Fundamentals - Test:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - System Design:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #     - Phase 4:
  #       - CP:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - CP - Test:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - Web Development:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  #       - Data Science:
  #         - learning_resources/CN_Series/Phase1/Aptitude/Aptitude.md
  # - Free Cources:
  #   - DSA:
  #     - Striver Series:
  #       - learning_resources/Free_Courses/Striver_Series/DSA.md
  #     - Love Babbar Series:
  #       - learning_resources/Free_Courses/Love_Babbar_Series/DSA.md
  #     - Apna College Series:
  #       - learning_resources/Free_Courses/Apna_College_Series/DSA.md
  #   - Theory:
  #     - Love Babbar Series:
  #       - learning_resources/Free_Courses/Love_Babbar_Series/DSA.md
  #     - Apna College Series:
  #       - learning_resources/Free_Courses/Apna_College_Series/DSA.md
  - Blog:
    - learning_resources/blog/index.md
  - About:
    - about/about.md
    - about/contributing.md
